<a href="https://colab.research.google.com/github/el-dAna/beginner-friendly-deeplearningIntro/blob/main/SignalProcessingLabPresentation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# DEEP LEARNING PRESENTATION
"""
This is the code to illustrate the theoritical explanation at #https://www.mathcha.io/editor
The main point to illustrate how the structure of a typical network works to my friends.
I look forward to constructive inputs from the instructors as well.

1. What is deep learning?

How does it learn?
2. Weight initialisation
3. Dot produucts
4. Activation functions

5. Number of neurons (Site to illustrate other concepts )
https://playground.tensorflow.org/#activation=tanh&batchSize=10&dataset=
spiral&regDataset=reg-gauss&learningRate=0.03&regularizationRate=0&noise=
0&networkShape=5,2,2&seed=0.27431&showTestData=false&discretize=false&percTrainData=
50&x=true&y=true&xTimesY=true&xSquared=true&ySquared=true&cosX=false&sinX=true&cosY=false&sinY=
true&collectStats=false&problem=regression&initZero=false&hideText=false

6. Loss functions
7. Back propagation

8. Looping
"""
import numpy as np
import matplotlib.pyplot as plt
#https://www.mathcha.io/editor


In [3]:
# initialises a 3x3 weigths matrix with zeros
W = np.zeros((3,3)) 

# initialises a 3x2 bias matrix with zeros
b = np.zeros((3,2))

# initialises a 3x3 input matrix
x = np.array([0,3,1,4,2,5]).reshape(3,2)

# initialises a 3x3 labels matrix
y = np.array([3, 9, 5, 11, 7, 13]).reshape(3,2)

# outputs formated matrices for better visualisation
print(f'{W} \n{x} \n{b} \n{y}')

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 
[[0 3]
 [1 4]
 [2 5]] 
[[0. 0.]
 [0. 0.]
 [0. 0.]] 
[[ 3  9]
 [ 5 11]
 [ 7 13]]


In [5]:

def compute_Z(W, x, b):
  """
  This function returns the dot product of W and X added to b
  Z = WX + b

  W : numpy array of weights
  x : numpy array of labels
  b : numpy array with labels

  returns Z: array-like
  """
  # Z = WX + b
  return np.dot(W, x) + b


# calling compute_Z and putting in the arguments. Visit https://www.mathcha.io/editor for more visualisation.
Z = compute_Z(W, x, b)
print(Z)


[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
def sigmoid(z):
  return 1/(1+np.exp(-z))

  

prediction = sigmoid(Z)
print(prediction)

In [ ]:
def MSE(y, y_hat):
  return (np.sum(np.square(y-y_hat))) / 6

  

mse = MSE(y, prediction)
print(mse)

In [ ]:
def get_derivatives(y, y_hat, x):
  dy_hat = np.multiply(np.multiply(-2, y_hat) , (y-y_hat))
  dz = np.multiply(y_hat, (1-y_hat))
  dLW = np.dot(dy_hat*dz, np.transpose(x))
  dLb = dy_hat*dz
  return dLW, dLb

  

dLW, dLb = get_derivatives(y, prediction, x)
print(dLW)
print(dLb)

In [ ]:
def update_parameters(W, b, dLW, dLb, alpha):
  updated_W = W - alpha*dLW
  updated_b = b - alpha*dLb
  return updated_W, updated_b

  

updated_W, updated_b = update_parameters(W, b, dLW, dLb, alpha = 0.01)
print(updated_W)
print(updated_b)

In [ ]:
def logistic_regression(x,y,W, b, alpha):
  temp_z = compute_Z(W, x, b) # Z = Wx + b
  temp_pred = sigmoid(temp_z) # prediction = sigmoid_z(bla bla)
  temp_error = MSE(y, temp_pred) # compute loss
  dLW, dLb = get_derivatives(y, temp_pred, x) # get derivatives
  return dLW, dLb, temp_error


def Model(x,y,epoch,alpha):
  W = np.zeros((3,3))
  b = np.zeros((3,2))
  pred_error = []
  for i in range(epoch):
    dLW, dLb, temp_pred_error = logistic_regression(x,y,W,b,alpha)
    pred_error.append(temp_pred_error)
    W, b = update_parameters(W, b, dLW, dLb, alpha)
  return W,b,pred_error


In [ ]:
epoch = 10
alpha = 0.01
updated_W, updated_b, pred_error = Model(x, y, epoch, alpha)

In [ ]:
Range = np.arange(epoch)
print(updated_W)
plt.plot(Range, pred_error)

In [ ]:
print(sigmoid(compute_Z(updated_W, x, updated_b)))
print(y)

In [ ]:
import tensorflow as tf
from tensorflow.keras import layers
from keras.models import Model, load_model
model = tf.keras.models.Sequential()
model.add(layers.Dense(units = 1, input_shape = [1]))
model.compile(loss = 'mean_squared_error', optimizer = 'sgd')
model.summary()

In [ ]:
x = np.array([0,1,2,3,4,5])#.reshape(3,2)
y = np.array([3, 5, 7, 9, 11, 13])#.reshape(3,2)
epochs = 1000


history = model.fit(x, y, epochs = epochs)

In [ ]:
import pandas as pd
pd.DataFrame(history.history).plot(figsize=(10,5))
plt.title('Beni görüyörseniz merhaba deyin :)')
plt.show()

In [ ]:
model.predict([2000]) # f(x) = 2x + 3